"use client";

import {
  ActivityIcon,
  BookOpenIcon,
  CalendarCheckIcon,
  CalendarDaysIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CircleCheckIcon,
  EllipsisIcon,
  FlameIcon,
  FootprintsIcon,
  HistoryIcon,
  InfoIcon,
  LayoutDashboardIcon,
  ListIcon,
  LoaderCircleIcon,
  LogOutIcon,
  PlusIcon,
  SettingsIcon,
  SparklesIcon,
  StarIcon,
  SunMediumIcon,
  TrendingDownIcon,
  TriangleAlertIcon,
  UtensilsIcon,
  WatchIcon,
  XIcon,
} from "@animateicons/react/lucide";

export const appIcons = {
  activity: ActivityIcon,
  alert: TriangleAlertIcon,
  book: BookOpenIcon,
  calendar: CalendarDaysIcon,
  calendarCheck: CalendarCheckIcon,
  check: CheckIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevron: ChevronRightIcon,
  circleCheck: CircleCheckIcon,
  close: XIcon,
  dashboard: LayoutDashboardIcon,
  ellipsis: EllipsisIcon,
  flame: FlameIcon,
  footprints: FootprintsIcon,
  history: HistoryIcon,
  info: InfoIcon,
  list: ListIcon,
  loader: LoaderCircleIcon,
  logout: LogOutIcon,
  plus: PlusIcon,
  settings: SettingsIcon,
  sparkles: SparklesIcon,
  star: StarIcon,
  sun: SunMediumIcon,
  trend: TrendingDownIcon,
  utensils: UtensilsIcon,
  watch: WatchIcon,
} as const;

export type TAppIconName = keyof typeof appIcons;

export const navIconByHref: Record<string, TAppIconName> = {
  "/overview": "dashboard",
  "/calories": "flame",
  "/meals": "utensils",
  "/workouts": "footprints",
  "/measurements": "activity",
};
